# Generated by Django 5.0.4 on 2024-04-11 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huertos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('direccion', models.CharField(max_length=256)),
                ('info', models.CharField(max_length=256)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huertos', to='huertos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256)),
                ('id_huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='huertos.huerto')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=256)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='huertos.usuario')),
                ('id_huerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huerto', to='huertos.huerto')),
            ],
        ),
    ]
